spring:
  datasource:
      api:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://192.168.114.63:3306/base?useUnicode=true&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=true
        username: root
        password: 123456
      base:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://192.168.114.63:3306/base?useUnicode=true&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=true
        username: root
        password: 123456

server:
  port: 8085
  servlet:
    context-path: /scheduler
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
##jwt配置
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800
