spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/db_netqiuzhi?useUnicode=true&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=true&characterEncoding=UTF-8
      username: root
      password: 123456
server:
  port: 8086
  servlet:
    context-path: /
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.vasp.cloud.security.admin.mapper: DEBUG